//! Word-level repair of glyphs the atlas cannot tell apart by shape.
//!
//! In this font `I` and `l` are both a plain ~3px bar; `l` is 1–2px taller, which
//! anti-aliasing and the brightness threshold routinely erase, so `lost` reads as `Iost`.
//! No bitmap gate can separate them reliably, but words can: a word is rewritten only when
//! it is *not* a known word and swapping some of its `I`/`l` makes it one. Unknown words
//! (nicknames, player names) are otherwise left alone, except that a capital `I` straight
//! after a lowercase letter becomes `l` — that sequence does not occur in game text.
//!
//! The known words live in `lexicon.txt` beside the glyph atlas, built by `analyzer lexicon`
//! from the labelled crops, the pokedex snapshots and `BATTLE_WORDS`. Only words containing
//! `I` or `l` matter, so only those are kept.

use anyhow::{Context, Result};
use std::collections::HashSet;
use std::fmt::Write as _;
use std::path::Path;

/// Characters the atlas confuses, swapped for each other.
const CONFUSABLE: [(char, char); 2] = [('I', 'l'), ('l', 'I')];
/// Words with more confusable glyphs than this are left as read (2^n variants).
const MAX_CONFUSABLE: usize = 6;

/// Battle-message vocabulary containing `I` or `l`, beyond what the snapshots name.
pub const BATTLE_WORDS: &[&str] = &[
    "I", "It", "It’s", "Its", "Itself", "In", "Into", "Is", "If", "Item", "Illusion", "all",
    "ally", "allies", "also", "always", "asleep", "badly", "blew", "blocked", "blown", "called",
    "calmed", "clear", "cleared", "clever", "collapsed", "completely", "critical", "cursed",
    "drastically", "effectively", "elevated", "failed", "fall", "fell", "fallen", "field",
    "fled", "flew", "flinch", "flinched", "fluffy", "fully", "gleaming", "glowing", "hail",
    "harshly", "heal", "healed", "healing", "health", "held", "helped", "helping", "hold",
    "holding", "horribly", "itself", "level", "light", "lightly", "like", "little", "lock",
    "locked", "long", "longer", "lost", "loafing", "lowered", "lucky", "normal", "only",
    "paralyzed", "paralysis", "play", "pulled", "real", "really", "released", "reveal",
    "revealed", "roll", "sharply", "sleep", "slept", "slightly", "slowly", "solid", "spell",
    "still", "sunlight", "switched", "take", "themselves", "totally", "twisted", "until",
    "unleashed", "vanished", "well", "while", "whole", "wild", "will", "yourself",
];

#[derive(Default)]
pub struct Lexicon {
    words: HashSet<String>,
}

fn is_confusable(c: char) -> bool {
    CONFUSABLE.iter().any(|(a, _)| *a == c)
}

fn has_confusable(w: &str) -> bool {
    w.chars().any(is_confusable)
}

fn capitalized(w: &str) -> String {
    let mut c = w.chars();
    c.next().map_or_else(String::new, |f| f.to_uppercase().chain(c).collect())
}

impl Lexicon {
    /// Load `path`; a missing file is an empty lexicon (no word-level repair).
    pub fn load(path: &Path) -> Result<Self> {
        if !path.exists() {
            return Ok(Self::default());
        }
        let src = std::fs::read_to_string(path)
            .with_context(|| format!("reading lexicon {}", path.display()))?;
        Ok(Self::from_words(src.lines().filter(|l| !l.is_empty() && !l.starts_with('#'))))
    }

    /// Every word (split on spaces and hyphens, punctuation trimmed) that contains a
    /// confusable glyph, also in sentence-initial capitalised form.
    pub fn from_words<'a>(texts: impl IntoIterator<Item = &'a str>) -> Self {
        let mut words = HashSet::new();
        for text in texts {
            for part in text.split([' ', '-']) {
                let w = core(part).1;
                let w = w.strip_suffix("’s").unwrap_or(w);
                if !w.is_empty() && has_confusable(w) {
                    words.insert(w.to_string());
                    words.insert(capitalized(w));
                }
            }
        }
        Self { words }
    }

    pub fn len(&self) -> usize {
        self.words.len()
    }

    pub fn is_empty(&self) -> bool {
        self.words.is_empty()
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        let mut sorted: Vec<&String> = self.words.iter().collect();
        sorted.sort();
        let mut out = String::from(
            "# analyzer lexicon — generated by `analyzer lexicon`; words containing I or l\n",
        );
        for w in sorted {
            writeln!(out, "{w}")?;
        }
        std::fs::write(path, out).with_context(|| format!("writing {}", path.display()))
    }

    fn known(&self, w: &str) -> bool {
        self.words.contains(w) || w.strip_suffix("’s").is_some_and(|s| self.words.contains(s))
    }

    /// `text` with each word's `I`/`l` confusions repaired where the lexicon can tell.
    pub fn fix(&self, text: &str) -> String {
        if !has_confusable(text) {
            return text.to_string();
        }
        let mut out = String::with_capacity(text.len());
        for (i, token) in text.split(' ').enumerate() {
            if i > 0 {
                out.push(' ');
            }
            for (j, part) in token.split('-').enumerate() {
                if j > 0 {
                    out.push('-');
                }
                let (lead, word, trail) = core(part);
                out.push_str(lead);
                out.push_str(&self.fix_word(word));
                out.push_str(trail);
            }
        }
        out
    }

    fn fix_word(&self, w: &str) -> String {
        if !has_confusable(w) || self.known(w) {
            return w.to_string();
        }
        let chars: Vec<char> = w.chars().collect();
        let spots: Vec<usize> = (0..chars.len()).filter(|&i| is_confusable(chars[i])).collect();
        if spots.len() <= MAX_CONFUSABLE {
            // Fewest swaps first; ties by position, so the result is deterministic.
            let mut masks: Vec<u32> = (1..1u32 << spots.len()).collect();
            masks.sort_by_key(|m| (m.count_ones(), *m));
            for m in masks {
                let mut v = chars.clone();
                for (bit, &i) in spots.iter().enumerate() {
                    if m & (1 << bit) != 0 {
                        v[i] = CONFUSABLE.iter().find(|(a, _)| *a == v[i]).unwrap().1;
                    }
                }
                let v: String = v.into_iter().collect();
                if self.known(&v) {
                    return v;
                }
            }
        }
        // Not a known word either way: only fix the impossible `lowercase, I`.
        let mut v = chars;
        for i in 1..v.len() {
            if v[i] == 'I' && v[i - 1].is_lowercase() {
                v[i] = 'l';
            }
        }
        v.into_iter().collect()
    }
}

/// Split `s` into leading punctuation, the word, and trailing punctuation. The word keeps
/// internal apostrophes (`It’s`); `’` at either end is punctuation.
fn core(s: &str) -> (&str, &str, &str) {
    let is_word = |c: char| c.is_alphanumeric();
    let start = s.find(is_word).unwrap_or(s.len());
    let end = s.rfind(is_word).map_or(start, |i| i + s[i..].chars().next().unwrap().len_utf8());
    (&s[..start], &s[start..end], &s[end..])
}

#[cfg(test)]
mod tests {
    use super::*;

    fn lex() -> Lexicon {
        Lexicon::from_words(BATTLE_WORDS.iter().copied().chain([
            "Venusaur lost some of its HP!",
            "The opposing Overqwil used Will-O-Wisp!",
            "Toxapex’s health is sapped by Leech Seed!",
            "Yertle fainted!",
            "Iron Head",
        ]))
    }

    #[test]
    fn repairs_confused_bars_in_known_words() {
        let l = lex();
        assert_eq!(l.fix("Venusaur Iost some of its HP!"), "Venusaur lost some of its HP!");
        assert_eq!(l.fix("YertIe’s Attack feII!"), "Yertle’s Attack fell!");
        assert_eq!(l.fix("The opposing Overqwil used WiII-O-Wisp!"), "The opposing Overqwil used Will-O-Wisp!");
        assert_eq!(l.fix("lt’s super effective!"), "It’s super effective!");
    }

    #[test]
    fn leaves_correct_and_unknown_words_alone() {
        let l = lex();
        for s in [
            "Venusaur lost some of its HP!",
            "The opposing Kingambit used Iron Head!",
            "It’s not very effective on Pyroar.",
            "The opposing STAR PLTNM fell asleep!",
            "Loggy sent out Ilima!",
        ] {
            assert_eq!(l.fix(s), s);
        }
    }

    #[test]
    fn unknown_words_lose_only_impossible_capitals() {
        assert_eq!(lex().fix("Go! MoIly!"), "Go! Molly!");
    }
}
